# backend/app/models/pedidos.py
from sqlalchemy import Column, Integer, String, DateTime, Date, Text, Numeric
from ..core.database import Base

class Pedido(Base):
    __tablename__ = "pedidos"

    id = Column(Integer, primary_key=True, index=True)
    codigo_pedido = Column(String(50))
    estado = Column(String(50))
    fecha_registro = Column(DateTime)
    cupon = Column(String(100))
    nombre_promocion = Column(String(255))
    codigo_erp = Column(String(100))
    dispositivo = Column(String(100))
    navegador = Column(String(100))
    sistema_operativo = Column(String(100))
    ip = Column(String(45))
    modelo_dispositivo = Column(String(100))
    usuario = Column(String(100))
    correo = Column(String(150))
    celular = Column(String(50))
    lista_precio = Column(String(100))
    vendedor = Column(String(100))
    sku = Column(String(100))
    codigo_corto = Column(String(100))
    producto = Column(String(255))
    presentacion = Column(String(255))
    subcategoria = Column(String(255))
    categoria = Column(String(255))
    cantidad = Column(Integer)
    precio = Column(Numeric(10, 2))
    precio_total = Column(Numeric(10, 2))
    almacen = Column(String(100))
    tipo_despacho = Column(String(100))
    direccion_entrega = Column(String(255))
    referencia = Column(String(255))
    distrito = Column(String(150))
    persona_contacto = Column(String(150))
    numero_contacto = Column(String(50))
    fecha_entrega = Column(Date)
    hora_entrega = Column(String(20))
    tipo_recibo = Column(String(50))
    numero_documento = Column(String(50))
    razon_social = Column(String(255))
    direccion_facturacion = Column(String(255))
    metodo_pago = Column(String(100))
    codigo_transaccion = Column(String(100))
    comentarios = Column(Text)
    dedicatoria = Column(Text)
    tarjeta_regalo = Column(String(50))
    subtotal = Column(Numeric(10, 2))
    recargo_envio = Column(Numeric(10, 2))
    total = Column(Numeric(10, 2))
    review_rating = Column(Integer)
