# backend/app/models/stock.py
from sqlalchemy import Column, Integer, String, Numeric, Text
from ..core.database import Base

class Stock(Base):
    __tablename__ = "stock"

    id = Column(Integer, primary_key=True, index=True)
    FS_COD_SUCU = Column(String(50))
    FS_DES_SUCU = Column(String(150))
    FS_COD_ALMA = Column(String(50))
    FS_DES_ALMA = Column(String(150))
    FS_COD_UBIC_ALMA = Column(String(50))
    FS_COD_CLAS_0001 = Column(String(50))
    FS_DES_CLAS_0001 = Column(String(150))
    FS_COD_CLAS_0002 = Column(String(50))
    FS_DES_CLAS_0002 = Column(String(150))
    FS_COD_CLAS_0003 = Column(String(50))
    FS_DES_CLAS_0003 = Column(String(150))
    FS_COD_CLAS_0004 = Column(String(50))
    FS_DES_CLAS_0004 = Column(String(150))
    FS_COD_MARC = Column(String(50))
    FS_DES_MARC = Column(String(150))
    FS_COD_ARTI = Column(String(50))
    FN_CAN_ACTU = Column(Numeric(18, 3))
    FS_DES_ARTI = Column(String(255))
    FS_DES_ARTI_LARG = Column(Text)
    FS_COD_UNME = Column(String(50))
    AGRUPACION = Column(String(100))
    FS_CLA_CLAS_PLAN = Column(String(50))
    FN_NUM_PESO = Column(Numeric(18, 3))
    FN_NUM_VOLU = Column(Numeric(18, 3))
    FS_COD_UNME_ALTE = Column(String(50))
    FN_CAN_ACTU_ALTE = Column(Numeric(18, 3))
    FS_COD_UNME_EMPA = Column(String(50))
    FN_CAN_EMPA = Column(Numeric(18, 3))
    FN_CAN_EMPA_UNID = Column(Numeric(18, 3))
    FS_SEL_UNID_MEDI = Column(String(50))
    FN_CAN_LOTE = Column(Numeric(18, 3))
    FS_STA_CANT_LOTE = Column(String(50))
    FS_COD_ARTI_ALTE = Column(String(50))
    FS_DES_TAMA = Column(String(100))
    FS_COD_GENE = Column(String(50))
    FS_COD_ATNI_AT01 = Column(String(50))
    FS_DES_ATNI_AT01 = Column(String(150))
    FS_COD_ATNI_NI01 = Column(String(50))
    FS_DES_ATNI_NI01 = Column(String(150))
    FS_COD_ATRI_0001 = Column(String(50))
    FS_DES_ATRI_0001 = Column(String(150))
    FS_COD_ATRI_0002 = Column(String(50))
    FS_DES_ATRI_0002 = Column(String(150))
    FS_COD_ATRI_0003 = Column(String(50))
    FS_DES_ATRI_0003 = Column(String(150))
    FS_COD_ATRI_0004 = Column(String(50))
    FS_DES_ATRI_0004 = Column(String(150))
    FS_DES_GENE = Column(String(255))
    FS_DES_RUTA_IMAG = Column(String(255))
    FS_DES_LABO = Column(String(150))
    FI_COD_EMPR = Column(String(50))
    FS_DES_EMPR = Column(String(150))
